services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres
    restart: always
    ports:
      - "30000:5432"
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=meet_me
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./migrations/001_init_tables.sql:/docker-entrypoint-initdb.d/001.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meet_me"]
      interval: 30s
      timeout: 10s
      retries: 5
