env: 'local' # local/docker/prod

http:
  host: '0.0.0.0'
  port: '8080'
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 60s
  bytes_limit: 1024
  max_limit: 10485760

postgresql:
  username: 'postgres'
  password: '12345'
  host: 'localhost' # localhost/postgresql
  port: '5432'
  database: 'meet'

redis:
  password: '12345'
  host: 'localhost' # localhost/redis
  port: '6379' 
  database: 0
  lfu_capacity: 10000
  expiration: 60s

s3:
  bucket_name: 'meet'
  photo_limit: 5